##name = input('What is your name?')
##print(name)
##print(type(name))
##number = input('What is your id')
##print(number)

x = str(1)
print(x)
print(type(x))
y = int(2.8)
print(y)
z = float('5')
print(z)
