math = int(input('Please input your Maths result   :'))
sci  = int(input('Please input your Science result :'))
eng  = int(input('Please input your English result :'))
thai = int(input('Please input your Science result :'))
subject = (math,sci,eng,thai)
print(subject)
total = sum(subject)
# total = subject[0]+subject[1]+subject[2]+subject[3]
print(total)
percent = total/100*len(subject)
print(percent,'%')
